<?php
/**
 * @version	$Id:	default.php 2013-08-26
 * @copyright		Copyright (C) 2013 Leonardo Alviarez - Edén Arreaza. All Rights Reserved.
 * @license			GNU General Public License version 3, or later
 * @note			Note : All ini files need to be saved as UTF-8 - No BOM
 */

defined('_JEXEC') or die;
JHtml::_('behavior.framework');
JHtml::_('bootstrap.framework');
$document = JFactory::getDocument();
$document->addScript(JURI::base()."media/jui/js/chosen.jquery.js");
$document->addStyleSheet(JURI::base()."/media/jui/css/chosen.css");
$document->addScriptDeclaration('
jQuery(document).ready(function(){
	jQuery(".chzn-select-currency").chosen({
		disable_search_threshold : 10,
		allow_single_deselect : true
  });

}); 
');
?>
<div>
<form id="conversor" action="" method="GET">
<?	
		$currencies = array(
		"ALL" => JText::_('MOD_TH_CURRENCY_CONVERTER_ALBANIA_LEK')." (ALL)",
		"DZD" => JText::_('MOD_TH_CURRENCY_CONVERTER_ALGERIA_DINAR')." (DZD)",
		"XAL" => JText::_('MOD_TH_CURRENCY_CONVERTER_ALUMINIUM_OUNCES')." (XAL)",
		"ARS" => JText::_('MOD_TH_CURRENCY_CONVERTER_ARGENTINA_PESO')." (ARS)",
		"AWG" => JText::_('MOD_TH_CURRENCY_CONVERTER_ARUBA_FLORIN')." (AWG)",
		"AUD" => JText::_('MOD_TH_CURRENCY_CONVERTER_AUSTRALIA_DOLLAR')." (AUD)",
		"BSD" => JText::_('MOD_TH_CURRENCY_CONVERTER_BAHAMAS_DOLLAR')." (BSD)",
		"BHD" => JText::_('MOD_TH_CURRENCY_CONVERTER_BAHRAINI_DINAR')." (BHD)",
		"BDT" => JText::_('MOD_TH_CURRENCY_CONVERTER_BANGLADESH_TAKA')." (BDT)",
		"BBD" => JText::_('MOD_TH_CURRENCY_CONVERTER_BARBADOS_DOLLAR')." (BBD)",
		"BYR" => JText::_('MOD_TH_CURRENCY_CONVERTER_BELARUS_RUBLE')." (BYR)",
		"BZD" => JText::_('MOD_TH_CURRENCY_CONVERTER_BELIZE_DOLLAR')." (BZD)",
		"BMD" => JText::_('MOD_TH_CURRENCY_CONVERTER_BERMUDA_DOLLAR')." (BMD)",
		"BTN" => JText::_('MOD_TH_CURRENCY_CONVERTER_BHUTAN_NGULTRUM')." (BTN)",
		"BOB" => JText::_('MOD_TH_CURRENCY_CONVERTER_BOLIVIAN_BOLIVIANO')." (BOB)",
		"BWP" => JText::_('MOD_TH_CURRENCY_CONVERTER_BOTSWANA_PULA')." (BWP)",
		"BRL" => JText::_('MOD_TH_CURRENCY_CONVERTER_BRAZILIAN_REAL')." (BRL)",
		"GBP" => JText::_('MOD_TH_CURRENCY_CONVERTER_BRITISH_POUND')." (GBP)",
		"BND" => JText::_('MOD_TH_CURRENCY_CONVERTER_BRUNEI_DOLLAR')." (BND)",
		"BGN" => JText::_('MOD_TH_CURRENCY_CONVERTER_BULGARIAN_LEV')." (BGN)",
		"MMK" => JText::_('MOD_TH_CURRENCY_CONVERTER_BURMA_KYAT')." (MMK)",
		"BIF" => JText::_('MOD_TH_CURRENCY_CONVERTER_BURUNDI_FRANC')." (BIF)",
		"KHR" => JText::_('MOD_TH_CURRENCY_CONVERTER_CAMBODIA_RIEL')." (KHR)",
		"CAD" => JText::_('MOD_TH_CURRENCY_CONVERTER_CANADIAN_DOLLAR')." (CAD)",
		"CVE" => JText::_('MOD_TH_CURRENCY_CONVERTER_CAPE_VERDE_ESCUDO')." (CVE)",
		"KYD" => JText::_('MOD_TH_CURRENCY_CONVERTER_CAYMAN_ISLANDS_DOLLAR')." (KYD)",
		"XOF" => JText::_('MOD_TH_CURRENCY_CONVERTER_CFA_FRANC')." (BCEAO) (XOF)",
		"XAF" => JText::_('MOD_TH_CURRENCY_CONVERTER_CFA_FRANC')." (BEAC) (XAF)",
		"CLP" => JText::_('MOD_TH_CURRENCY_CONVERTER_CHILEAN_PESO')." (CLP)",
		"CNY" => JText::_('MOD_TH_CURRENCY_CONVERTER_CHINESE_YUAN')." (CNY)",
		"COP" => JText::_('MOD_TH_CURRENCY_CONVERTER_COLOMBIAN_PESO')." (COP)",
		"KMF" => JText::_('MOD_TH_CURRENCY_CONVERTER_COMOROS_FRANC')." (KMF)",
		"XCP" => JText::_('MOD_TH_CURRENCY_CONVERTER_COPPER_POUNDS')." (XCP)",
		"CRC" => JText::_('MOD_TH_CURRENCY_CONVERTER_COSTA_RICA_COLON')." (CRC)",
		"HRK" => JText::_('MOD_TH_CURRENCY_CONVERTER_CROATIAN_KUNA')." (HRK)",
		"CUP" => JText::_('MOD_TH_CURRENCY_CONVERTER_CUBAN_PESO')." (CUP)",
		"CYP" => JText::_('MOD_TH_CURRENCY_CONVERTER_CYPRUS_POUND')." (CYP)",
		"CZK" => JText::_('MOD_TH_CURRENCY_CONVERTER_CZECH_KORUNA')." (CZK)",
		"DKK" => JText::_('MOD_TH_CURRENCY_CONVERTER_DANISH_KRONE')." (DKK)",
		"DJF" => JText::_('MOD_TH_CURRENCY_CONVERTER_DIJBOUTI_FRANC')." (DJF)",
		"DOP" => JText::_('MOD_TH_CURRENCY_CONVERTER_DOMINICAN_PESO')." (DOP)",
		"XCD" => JText::_('MOD_TH_CURRENCY_CONVERTER_EAST_CARIBBEAN_DOLLAR')." (XCD)",
		"ECS" => JText::_('MOD_TH_CURRENCY_CONVERTER_ECUADOR_SUCRE')." (ECS)",
		"EGP" => JText::_('MOD_TH_CURRENCY_CONVERTER_EGYPTIAN_POUND')." (EGP)",
		"SVC" => JText::_('MOD_TH_CURRENCY_CONVERTER_EL_SALVADOR_COLON')." (SVC)",
		"ERN" => JText::_('MOD_TH_CURRENCY_CONVERTER_ERITREA_NAKFA')." (ERN)",
		"EEK" => JText::_('MOD_TH_CURRENCY_CONVERTER_ESTONIAN_KROON')." (EEK)",
		"ETB" => JText::_('MOD_TH_CURRENCY_CONVERTER_ETHIOPIAN_BIRR')." (ETB)",
		"EUR" => JText::_('MOD_TH_CURRENCY_CONVERTER_EURO')." (EUR)",
		"FKP" => JText::_('MOD_TH_CURRENCY_CONVERTER_FALKLAND_ISLANDS_POUND')." (FKP)",
		"FJD" => JText::_('MOD_TH_CURRENCY_CONVERTER_FIJI_DOLLAR')." (FJD)",
		"GMD" => JText::_('MOD_TH_CURRENCY_CONVERTER_GAMBIAN_DALASI')." (GMD)",
		"GHC" => JText::_('MOD_TH_CURRENCY_CONVERTER_GHANIAN_CEDI')." (GHC)",
		"GIP" => JText::_('MOD_TH_CURRENCY_CONVERTER_GIBRALTAR_POUND')." (GIP)",
		"XAU" => JText::_('MOD_TH_CURRENCY_CONVERTER_GOLD_OUNCES')." (XAU)",
		"GTQ" => JText::_('MOD_TH_CURRENCY_CONVERTER_GUATEMALA_QUETZAL')." (GTQ)",
		"GNF" => JText::_('MOD_TH_CURRENCY_CONVERTER_GUINEA_FRANC')." (GNF)",
		"GYD" => JText::_('MOD_TH_CURRENCY_CONVERTER_GUYANA_DOLLAR')." (GYD)",
		"HTG" => JText::_('MOD_TH_CURRENCY_CONVERTER_HAITI_GOURDE')." (HTG)",
		"HNL" => JText::_('MOD_TH_CURRENCY_CONVERTER_HONDURAS_LEMPIRA')." (HNL)",
		"HKD" => JText::_('MOD_TH_CURRENCY_CONVERTER_HONG_KONG_DOLLAR')." (HKD)",
		"HUF" => JText::_('MOD_TH_CURRENCY_CONVERTER_HUNGARIAN_FORINT')." (HUF)",
		"ISK" => JText::_('MOD_TH_CURRENCY_CONVERTER_ICELAND_KRONA')." (ISK)",
		"INR" => JText::_('MOD_TH_CURRENCY_CONVERTER_INDIAN_RUPEE')." (INR)",
		"IDR" => JText::_('MOD_TH_CURRENCY_CONVERTER_INDONESIAN_RUPIAH')." (IDR)",
		"IRR" => JText::_('MOD_TH_CURRENCY_CONVERTER_IRAN_RIAL')." (IRR)",
		"IQD" => JText::_('MOD_TH_CURRENCY_CONVERTER_IRAQI_DINAR')." (IQD)",
		"ILS" => JText::_('MOD_TH_CURRENCY_CONVERTER_ISRAELI_SHEKEL')." (ILS)",
		"JMD" => JText::_('MOD_TH_CURRENCY_CONVERTER_JAMAICAN_DOLLAR')." (JMD)",
		"JPY" => JText::_('MOD_TH_CURRENCY_CONVERTER_JAPANESE_YEN')." (JPY)",
		"JOD" => JText::_('MOD_TH_CURRENCY_CONVERTER_JORDANIAN_DINAR')." (JOD)",
		"KZT" => JText::_('MOD_TH_CURRENCY_CONVERTER_KAZAKHSTAN_TENGE')." (KZT)",
		"KES" => JText::_('MOD_TH_CURRENCY_CONVERTER_KENYAN_SHILLING')." (KES)",
		"KRW" => JText::_('MOD_TH_CURRENCY_CONVERTER_KOREAN_WON')." (KRW)",
		"KWD" => JText::_('MOD_TH_CURRENCY_CONVERTER_KUWAITI_DINAR')." (KWD)",
		"LAK" => JText::_('MOD_TH_CURRENCY_CONVERTER_LAO_KIP')." (LAK)",
		"LVL" => JText::_('MOD_TH_CURRENCY_CONVERTER_LATVIAN_LAT')." (LVL)",
		"LBP" => JText::_('MOD_TH_CURRENCY_CONVERTER_LEBANESE_POUND')." (LBP)",
		"LSL" => JText::_('MOD_TH_CURRENCY_CONVERTER_LESOTHO_LOTI')." (LSL)",
		"LRD" => JText::_('MOD_TH_CURRENCY_CONVERTER_LIBERIAN_DOLLAR')." (LRD)",
		"LYD" => JText::_('MOD_TH_CURRENCY_CONVERTER_LIBYAN_DINAR')." (LYD)",
		"LTL" => JText::_('MOD_TH_CURRENCY_CONVERTER_LITHUANIAN_LITA')." (LTL)",
		"MOP" => JText::_('MOD_TH_CURRENCY_CONVERTER_MACAU_PATACA')." (MOP)",
		"MKD" => JText::_('MOD_TH_CURRENCY_CONVERTER_MACEDONIAN_DENAR')." (MKD)",
		"MWK" => JText::_('MOD_TH_CURRENCY_CONVERTER_MALAWI_KWACHA')." (MWK)",
		"MYR" => JText::_('MOD_TH_CURRENCY_CONVERTER_MALAYSIAN_RINGGIT')." (MYR)",
		"MVR" => JText::_('MOD_TH_CURRENCY_CONVERTER_MALDIVIES_RUFIYAA')." (MVR)",
		"MTL" => JText::_('MOD_TH_CURRENCY_CONVERTER_MALTESE_LIRA')." (MTL)",
		"MRO" => JText::_('MOD_TH_CURRENCY_CONVERTER_MAURITANIA_OUGULYA')." (MRO)",
		"MUR" => JText::_('MOD_TH_CURRENCY_CONVERTER_MAURITIUS_RUPEE')." (MUR)",
		"MXN" => JText::_('MOD_TH_CURRENCY_CONVERTER_MEXICAN_PESO')." (MXN)",
		"MDL" => JText::_('MOD_TH_CURRENCY_CONVERTER_MOLDOVAN_LEU')." (MDL)",
		"MNT" => JText::_('MOD_TH_CURRENCY_CONVERTER_MONGOLIAN_TUGRIK')." (MNT)",
		"MAD" => JText::_('MOD_TH_CURRENCY_CONVERTER_MOROCCAN_DIRHAM')." (MAD)",
		"NAD" => JText::_('MOD_TH_CURRENCY_CONVERTER_NAMIBIAN_DOLLAR')." (NAD)",
		"NPR" => JText::_('MOD_TH_CURRENCY_CONVERTER_NEPALESE_RUPEE')." (NPR)",
		"ANG" => JText::_('MOD_TH_CURRENCY_CONVERTER_NETH_ANTILLES_GUILDER')." (ANG)",
		"TRY" => JText::_('MOD_TH_CURRENCY_CONVERTER_TURKISH_LIRA')." (TRY)",
		"NZD" => JText::_('MOD_TH_CURRENCY_CONVERTER_NEW_ZELAND_DOLLAR')." (NZD)",
		"NIO" => JText::_('MOD_TH_CURRENCY_CONVERTER_NICARAGUA_CORDOBA')." (NIO)",
		"NGN" => JText::_('MOD_TH_CURRENCY_CONVERTER_NIGERIAN_NAIRA')." (NGN)",
		"KPW" => JText::_('MOD_TH_CURRENCY_CONVERTER_NORTH_KOREAN_WON')." (KPW)",
		"NOK" => JText::_('MOD_TH_CURRENCY_CONVERTER_NORWEGIAN_KRONE')." (NOK)",
		"OMR" => JText::_('MOD_TH_CURRENCY_CONVERTER_OMANI_RIAL')." (OMR)",
		"XPF" => JText::_('MOD_TH_CURRENCY_CONVERTER_PACIFIC_FRANC')." (XPF)",
		"PKR" => JText::_('MOD_TH_CURRENCY_CONVERTER_PAKISTANI_RUPEE')." (PKR)",
		"XPD" => JText::_('MOD_TH_CURRENCY_CONVERTER_PALLANDIUM_OUNCES')." (XPD)",
		"PAB" => JText::_('MOD_TH_CURRENCY_CONVERTER_PANAMA_BALBOA')." (PAB)",
		"PGK" => JText::_('MOD_TH_CURRENCY_CONVERTER_PAPUA_NEW_GUINEA_KINA')." (PGK)",
		"PYG" => JText::_('MOD_TH_CURRENCY_CONVERTER_PARAGUAYAN_GUARANI')." (PYG)",
		"PEN" => JText::_('MOD_TH_CURRENCY_CONVERTER_PERUVIAN_SOL')." (PEN)",
		"PHP" => JText::_('MOD_TH_CURRENCY_CONVERTER_PHILIPPINE_PESO')." (PHP)",
		"XPT" => JText::_('MOD_TH_CURRENCY_CONVERTER_PLATINUM_OUNCES')." (XPT)",
		"PLN" => JText::_('MOD_TH_CURRENCY_CONVERTER_POLISH_ZLOTY')." (PLN)",
		"QAR" => JText::_('MOD_TH_CURRENCY_CONVERTER_QATAR_RIAL')." (QAR)",
		"RON" => JText::_('MOD_TH_CURRENCY_CONVERTER_ROMANIAN_LEU')." (RON)",
		"RUB" => JText::_('MOD_TH_CURRENCY_CONVERTER_RUSSIAN_RUBLE')." (RUB)",
		"RWF" => JText::_('MOD_TH_CURRENCY_CONVERTER_RWANDA_FRANC')." (RWF)",
		"WST" => JText::_('MOD_TH_CURRENCY_CONVERTER_SAMOA_TALA')." (WST)",
		"STD" => JText::_('MOD_TH_CURRENCY_CONVERTER_SAO_TOME_DOBRA')." (STD)",
		"SAR" => JText::_('MOD_TH_CURRENCY_CONVERTER_SAUDI_RIYAL')." (SAR)",
		"SCR" => JText::_('MOD_TH_CURRENCY_CONVERTER_SEYCHELLES_RUPPE')." (SCR)",
		"SLL" => JText::_('MOD_TH_CURRENCY_CONVERTER_SIERRA_LEONE_LEONE')." (SLL)",
		"XAG" => JText::_('MOD_TH_CURRENCY_CONVERTER_SILVER_OUNCES')." (XAG)",
		"SGD" => JText::_('MOD_TH_CURRENCY_CONVERTER_SINGAPORE_DOLLAR')." (SGD)",
		"SKK" => JText::_('MOD_TH_CURRENCY_CONVERTER_SLOVAK_KORUNA')." (SKK)",
		"SIT" => JText::_('MOD_TH_CURRENCY_CONVERTER_SLOVENIAN_TOLAR')." (SIT)",
		"SBD" => JText::_('MOD_TH_CURRENCY_CONVERTER_SOLOMON_ISLANDS_DOLLAR')." (SBD)",
		"SOS" => JText::_('MOD_TH_CURRENCY_CONVERTER_SOMALI_SHILLING')." (SOS)",
		"ZAR" => JText::_('MOD_TH_CURRENCY_CONVERTER_SOUTH_AFRICAN_RAND')." (ZAR)",
		"LKR" => JText::_('MOD_TH_CURRENCY_CONVERTER_SRI_LANKA_RUPEE')." (LKR)",
		"SHP" => JText::_('MOD_TH_CURRENCY_CONVERTER_ST_HELENA_POUND')." (SHP)",
		"SDD" => JText::_('MOD_TH_CURRENCY_CONVERTER_SUDANESE_DINAR')." (SDD)",
		"SZL" => JText::_('MOD_TH_CURRENCY_CONVERTER_SWAZILAND_LILANGENI')." (SZL)",
		"SEK" => JText::_('MOD_TH_CURRENCY_CONVERTER_SWEDISH_KRONA')." (SEK)",
		"CHF" => JText::_('MOD_TH_CURRENCY_CONVERTER_SWISS_FRANC')." (CHF)",
		"SYP" => JText::_('MOD_TH_CURRENCY_CONVERTER_SYRIAN_POUND')." (SYP)",
		"TWD" => JText::_('MOD_TH_CURRENCY_CONVERTER_TAIWAN_DOLLAR')." (TWD)",
		"TZS" => JText::_('MOD_TH_CURRENCY_CONVERTER_TANZANIAN_SHILLING')." (TZS)",
		"THB" => JText::_('MOD_TH_CURRENCY_CONVERTER_THAI_BAHT')." (THB)",
		"TOP" => JText::_('MOD_TH_CURRENCY_CONVERTER_TONGA_PA-ANGA')." (TOP)",
		"TTD" => JText::_('MOD_TH_CURRENCY_CONVERTER_TRINIDAD_AND_TOBAGO_DOLLAR')." (TTD)",
		"TND" => JText::_('MOD_TH_CURRENCY_CONVERTER_TUNISIAN_DINAR')." (TND)",
		"USD" => JText::_('MOD_TH_CURRENCY_CONVERTER_US_DOLLAR')." (USD)",
		"AED" => JText::_('MOD_TH_CURRENCY_CONVERTER_UAE_DIRHAM')." (AED)",
		"UGX" => JText::_('MOD_TH_CURRENCY_CONVERTER_UGANDAN_SHILLING')." (UGX)",
		"UAH" => JText::_('MOD_TH_CURRENCY_CONVERTER_UKRAINIAN_HRYVNIA')." (UAH)",
		"UYU" => JText::_('MOD_TH_CURRENCY_CONVERTER_URUGUAYAN_PESO')." (UYU)",
		"VUV" => JText::_('MOD_TH_CURRENCY_CONVERTER_VANUATU_VATU')." (VUV)",
		"VEF" => JText::_('MOD_TH_CURRENCY_CONVERTER_VENEZUELAN_BOLIVAR')." (VEF)",
		"VND" => JText::_('MOD_TH_CURRENCY_CONVERTER_VIETNAM_DONG')." (VND)",
		"YER" => JText::_('MOD_TH_CURRENCY_CONVERTER_YEMEN_RIYAL')." (YER)",
		"ZMK" => JText::_('MOD_TH_CURRENCY_CONVERTER_ZAMBIAN_KWACHA')." (ZMK)",
		"ZWD" => JText::_('MOD_TH_CURRENCY_CONVERTER_ZIMBABWE_DOLLAR')." (ZWD)"
		);
		
		$currency = JRequest::getVar('currency');
		if(isset($currency))
			$value=$currency;	
		else
			$value='USD';
		
		$attr = array(
	        'id'          => 'currency',
	        'list.select' => $value,
	         'list.attr'   => 'class="chzn-select-currency" '
		    . 'data-no_results_text="' . JText::_('MOD_TH_CURRENCY_CONVERTER_NO_RESULTS') . '" '
		    . 'data-placeholder="' . JText::_('MOD_TH_CURRENCY_CONVERTER_SELECT_CURRENCY') . '" '
        );
		$str = JHtml::_('select.genericlist', $currencies, 'currency', $attr);
	    echo $str;

	
?>	
	<button type="submit">Convertir</button>
	</form>	
</div>
